name: 'Commit and Create a Pull Request'
description: 'Commit and Create a Pull Request'
inputs:
  github-token:
    description: 'The GitHub Token'
    required: true
    default: '${{ github.token }}'
  base-branch:
    description: 'base branch'
    required: true
    default: '${{ github.ref_name }}'
  head-branch:
    description: 'head branch'
  title:
    description: 'The title of pull requests'
  body:
    description: 'The body of pull requests'
  commit-message:
    description: 'The commit message'
outputs:
  commit-url:
    description: "The URL of a commit created"
    value: ${{ steps.commit-and-create-pr.outputs.commit-url }}
  pr-url:
    description: "The URL of a pull request created"
    value: ${{ steps.commit-and-create-pr.outputs.pr-url }}
runs:
  using: "composite"
  steps:
    - id: commit-and-create-pr
      run: ${{ github.action_path }}/commit-and-create-pr.sh
      shell: bash
      env:
        GITHUB_TOKEN: '${{ inputs.github-token }}'
        INPUT_BASE_BRANCH: '${{ inputs.base-branch }}'
        INPUT_HEAD_BRANCH: '${{ inputs.head-branch }}'
        INPUT_TITLE: '${{ inputs.title }}'
        INPUT_BODY: '${{ inputs.body }}'
        INPUT_COMMIT_MESSAGE: '${{ inputs.commit-message }}'
